name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: ${{ github.repository }}
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.DEPLOY_TOKEN }}
          submodules: recursive

      - name: Pull Latest Changes to Prevent Conflicts
        run: |
          git pull origin main || echo "No pull needed or conflict resolved"

      - name: Clean Up Git Issues and Submodules
        run: |
          git submodule deinit -f .
          git submodule update --init --recursive || echo "No submodules or already updated"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Generate Project Files and Build Artifacts
        run: |
          mkdir -p project_files
          echo "Sample project file for testing" > project_files/test_file.txt

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "🚀 Automated build and deployment" || echo "No changes to commit"
          git pull origin main --rebase
          git push https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/${{ github.repository }}.git main --force
